### ISSUE TITLE
OIDN denoiser crashes Blender

### ISSUE THREAD

**Issue by Blempis** [LuxCoreRender/BlendLuxCore#493] opened 2020-06-24 10:51 UTC
Blender 2.83 crashes after rendering if OIDN denoiser is selected.

[WithTheseSettingsItCrashes_4517_autosave.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4824834/WithTheseSettingsItCrashes_4517_autosave.zip)

Blender 2.82 can handle the same file.

Ubuntu 18.04

**Comment by Dade916** [comment] 2020-06-24 10:54
I assume this is a duplicate of #423

**Closed by Dade916** 2020-06-24 10:54 UTC
Labels: duplicate
