### ISSUE TITLE
Luxcore Blender 2.83

### ISSUE THREAD

**Issue by Ibo0o0o** [LuxCoreRender/BlendLuxCore#561] opened 2020-09-05 23:07 UTC
I have the following error :  OpenCL driver API error (code -30, file:/Users/runner/work/1/s/src/luxrays/utils/ocl.cpp, line: 366): CL_INVALID_VALUE

Don't know what to do

**Comment by CodeFHD** [comment] 2020-09-14 13:41
Sounds like a duplicate of [LuxCore Issue #439](https://github.com/LuxCoreRender/LuxCore/issues/439)

You can try to reinstall the GPU driver. If you have an Nvidia card, you can switch to using CUDA instead of OpenCL in the addon preferences.

**Comment by Ibo0o0o** [comment] 2020-09-14 13:55
Working on macOS. No Nvidia for me

**Comment by Dade916** [comment] 2020-09-16 15:19
Does LuxMark work ?

**Comment by Ibo0o0o** [comment] 2020-09-16 17:12
No. It doesn’t, The strange thin is that LuxCore has worked.

**Comment by Dade916** [comment] 2020-09-16 18:25
Some time OS updates/security patches can break GPU driver installation (it has happened more the once on Windows). You should try to re-install GPU driver (if there is such thing on MacOS).

**Comment by Ibo0o0o** [comment] 2020-09-16 18:28
Thanks I wil trie

**Closed** 2020-09-25 10:28 UTC
Labels: question
