### ISSUE TITLE
ImageMap file doesn't exist

### ISSUE THREAD

**Issue by PavelBlend** [LuxCoreRender/BlendLuxCore#207] opened 2018-09-06 18:24 UTC
#### System Information

OS: Windows 7 64 bit
GPU: None

#### Software Version

* Blender version: 2.79b (f4dc9f9d68b)
* LuxCore version: 2.1 alpha3

#### Error message from Blender console

```[Engine/Final] Rendering layer "RenderLayer"
[Exporter] create_session
[SDL][12.682] Camera type: perspective
[SDL][12.682] Camera position: Point[1.22922, -5.48722, 1.07203]
[SDL][12.682] Camera target: Point[0.998509, -4.53642, 0.865288]
[SDL][12.682] Camera clipping plane disabled
converting mesh: Cube
[SDL][12.682] Texture definition: 244035256
[SDL][12.682] Reading texture map: C:\Users\Pavel\Desktop\luxcore_test_textures\
╤В╨╡╤Б╤В╨╛╨▓╨░╤П ╤В╨╡╨║╤Б╤В╤Г╤А╨░.png
Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\BlendLuxCore\engine\__init__.py", line 55, in render_final
    final.render(self, scene)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\BlendLuxCore\engine\final.py", line 37, in render
    _render_layer(engine, scene)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\BlendLuxCore\engine\final.py", line 49, in _render_layer
    engine.session = engine.exporter.create_session(engine=engine)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\BlendLuxCore\export\__init__.py", line 148, in create_session
    luxcore_scene.Parse(scene_props)
RuntimeError: ImageMap file doesn't exist: C:\Users\Pavel\Desktop\luxcore_test_t
extures\╤В╨╡╤Б╤В╨╛╨▓╨░╤П ╤В╨╡╨║╤Б╤В╤Г╤А╨░.png
ERROR: ImageMap file doesn't exist: C:\Users\Pavel\Desktop\luxcore_test_textures
\╤В╨╡╤Б╤В╨╛╨▓╨░╤П ╤В╨╡╨║╤Б╤В╤Г╤А╨░.png
╨Ю╤И╨╕╨▒╨║╨░: ImageMap file doesn't exist: C:\Users\Pavel\Desktop\luxcore_test_t
extures\╤В╨╡╤Б╤В╨╛╨▓╨░╤П ╤В╨╡╨║╤Б╤В╤Г╤А╨░.png
```

#### Short description of error
Error while pressing F12 (Render). If you set a texture containing Cyrillic in the name.

#### Exact steps for others to reproduce the error
Example scene:
[luxcore_test_textures.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/2548926/luxcore_test_textures.zip)
* Open .blend
* Press F12

**Comment by Theverat** [comment] 2018-09-19 11:12
I could not reproduce this problem on Linux.
Maybe it is a Windows-specific issue.
I will look into it when I get back to my Windows PC in a few days.

**Comment by Theverat** [comment] 2018-11-05 14:58
I can reproduce the problem on Windows.

**Comment by Theverat** [comment] 2018-11-05 15:04
@Dade916 this looks like a LuxCore problem to me, BlendLuxCore itself finds the file and says it exists, only LuxCore fails at loading.

**Comment by Dade916** [comment] 2018-11-05 15:29
I will check but it should be a known problem: https://github.com/LuxCoreRender/LuxCore/issues/103

The source was in Boost not supporting 16bit char sets on Linux  (it was on Windows). It is a problem a bit cumbersome to investigate for me because I use a latin locale but I will check.

**Comment by Dade916** [comment] 2018-11-05 15:44
On my Linux, BlendLuxCore doesn't handle the file name too:

```
[Engine/Final] Rendering layer "RenderLayer"
[Exporter] Creating session
[SDL][48.083] Camera type: perspective
[SDL][48.084] Camera position: Point[1.22922, -5.48722, 1.07203]
[SDL][48.085] Camera target: Point[0.998509, -4.53642, 0.865288]
[SDL][48.085] Camera clipping plane disabled
WARNING: Node "Imagemap" in tree "Material": Could not find image "тестовая текстура.png" at path "//ÔÑßÔ«óá´ ÔÑ¬ßÔÒÓá.png" (Not an existing file: "/home/david/tmp/locale/ÔÑßÔ«óá´ ÔÑ¬ßÔÒÓá.png")
```

The warning should come from BlendLuxCore. Anyway, like I wrote before, it is know limit of current API, it uses 8bit char strings. There may be a way to convert 16bit strings in 8bit format so an application with 8bit strings can still read the file but, if it exists, it is OS specific.

**Comment by Dade916** [comment] 2018-11-05 15:47
Something like https://stackoverflow.com/questions/1207457/convert-a-unicode-string-to-a-string-in-python-containing-extra-symbols but I don't know what type of encode Windows uses for file names (if it uses one).

**Comment by MrHorseless** [comment] 2020-03-21 17:06
![NIMGDC6wu7](https://user-images.githubusercontent.com/62478096/77231994-91162400-6bc8-11ea-8f2c-2c3f62a010fc.png)
Same problem
ImageMap file doesn't exist: C:\Users\Пользователь\Desktop\TexturesCom_WoodPlanksBare0466_2_M.jpg

**Comment by MrHorseless** [comment] 2020-03-21 17:14
> Same problem
> ImageMap file doesn't exist: C:\Users\Пользователь\Desktop\TexturesCom_WoodPlanksBare0466_2_M.jpg

So when I saved my image in just Disk(C) it worked

**Comment by Dade916** [comment] 2020-03-23 10:27
> > Same problem
> > ImageMap file doesn't exist: C:\Users\Пользователь\Desktop\TexturesCom_WoodPlanksBare0466_2_M.jpg
> 
> So when I saved my image in just Disk(C) it worked

Yes, the problem is the "Пользователь" string, no latin char sets are not currently supported: LuxCoreRender/LuxCore#103

**Comment by Dade916** [comment] 2020-03-23 10:29
Duplicate of LuxCoreRender/LuxCore#103

**Closed by Dade916** 2020-03-23 10:29 UTC
Labels: bug
