### ISSUE TITLE
material on this mesh makes luxcore crash so hard it closes blender 

### ISSUE THREAD

**Issue by matthewv1998** [LuxCoreRender/BlendLuxCore#418] opened 2020-04-09 10:19 UTC
so, even flipping over to materal preview causes the crash.

.blend file: 
[BROKEN PARTS.zip](https://github.com/LuxCoreRender/BlendLuxCore/files/4455578/BROKEN.PARTS.zip)

Steps to reproduce: i dont know how this material is breaking luxcore, but it is

OS: ubuntu 18.04
Blender version: 2.82.7
LuxCore version: 2.3

**Comment by Theverat** [comment] 2020-05-04 19:38
Might be a duplicate of https://github.com/LuxCoreRender/LuxCore/issues/345

**Comment by Theverat** [comment] 2020-06-26 16:11
I can not reproduce a crash on Windows 10.
It might be a Linux only problem, can anyone else with Linux test?

(TIF file loading is broken on my end as well, but I'm not sure yet if this is an issue of my build environment, see https://github.com/LuxCoreRender/LuxCore/issues/345#issuecomment-627561773)

**Comment by Dade916** [comment] 2020-06-27 09:37
The scene is working fine here with v2.4 and Linux. @matthewv1998, you should try to install the under development v2.4 and check if it works for you too: https://forums.luxcorerender.org/viewtopic.php?f=9&t=736

**Closed** 2020-06-30 08:58 UTC
