### ISSUE TITLE
Can't turn off image sequence detection for the first image from enumerated textures (Blender 2.79)

### ISSUE THREAD

**Issue by thima2017** [LuxCoreRender/BlendLuxCore#301] opened 2019-09-26 09:52 UTC
To reproduce:
0) You need an enumerated sequence of images in the same directory. I have it named from image0001.png to image0004.png.
1) Add image texture node in the materials node editor.
2) Try to use the first image only without sequence detection.
Sequence detection is not avoidable for the first image. But it is for any other image in the directory.

**Comment by Theverat** [comment] 2019-09-30 08:40
I can not reproduce this problem: https://youtu.be/PNE-Nfcrl3A
What are you doing differently?

**Comment by thima2017** [comment] 2019-09-30 09:26
I used Blender 2.79. I'm sorry I'll edit the title.

**Comment by Theverat** [comment] 2020-11-04 13:10
Since this is about Blender 2.79, which is not supported by newer versions of our addon for quite a while now, I'll close this issue.
If a developer comes around who wants to fix it, or if you can re-produce this problem in a currently supported Blender version, feel free to re-open it.

**Closed by Theverat** 2020-11-04 13:10 UTC
