### ISSUE TITLE
'Object' object has no attribute 'cycles_visibility' 

### ISSUE THREAD

**Issue by tolozine** [LuxCoreRender/BlendLuxCore#742] opened 2021-12-24 04:15 UTC
'Object' object has no attribute 'cycles_visibility'
![image](https://user-images.githubusercontent.com/8479450/147315366-48d5f3ba-13ab-4292-a226-81617a36306d.png)
![image](https://user-images.githubusercontent.com/8479450/147315389-77044cd5-bc40-4735-93e3-67d5013c4b4b.png)
blender 3.0.0
mac os 10.14.6 (18G103)

**Comment by Axelaredz** [comment] 2021-12-27 20:35
same thing 'Object' object has no attribute 'cycles_visibility'
BlendLuxCore latest build 22.12.21
Blender 3.0.0
Ubuntu 21.10

**Comment by neo2068** [comment] 2021-12-27 21:42
Yes, it is a known issue. The current Blendluxcore version 2.6 is compatible with Blender 2.93LTS. There are still compability problems with Blender 3.0 which will be adressed in the near future.

**Comment by neo2068** [comment] 2021-12-28 09:46
I fixed the object visibility problem. There are more issues to fix, i.e. there is a incompatibility of dependencies which crashes the addon under windows.

**Comment by SteffenDuenner** [comment] 2021-12-28 12:10
Thanks for fixing this. I can successfully install and activate the addon in Linux with Blender 3.0 and Blender master (daily 3.1).
I can also render with LuxCore CPU and GPU.
The funny thing is that as soon as the BlendLuxCore addon is loaded I can no longer render with Cycles GPU (Optix).
I get this error msg:

![Screenshot from 2021-12-28 13-03-55](https://user-images.githubusercontent.com/33224667/147564935-21aeceda-8e9c-4199-b3b2-ef0a8650c093.png)

**Comment by neo2068** [comment] 2021-12-28 13:05
> 

That is strange and I don't think that the issue is related to the BlendLuxCore addon. Please check if it only happens when the addon is activated and open an dedicated issue if it is the case. I will close this issue as it is fixed.

**Closed by neo2068** 2021-12-28 13:05 UTC
