### ISSUE TITLE
RT Viewport Engine output for Visualization?

### ISSUE THREAD

**Issue by giacometti777** [LuxCoreRender/BlendLuxCore#476] opened 2020-06-03 17:40 UTC
If we could somehow export denoised Viewport frames directly it would be a gamechanger imo. Proper rendering looks great but scene export time per frame kills the iteration process for artists - especially when many aesthetics are not represented in solid shading renders. I am currently using this hack to grab these frames and even this works a charm: https://blenderartists.org/t/cycles-dynamic-bvh/655915

Could someone even create a little script to capture the viewport window and output as stills while ticking through the timeline automatically? Ideally some alternate version of "Viewport Render" would be ideal though and definitely put Lux ahead of many other renderers for practicality (including Cycles)! Thanks for considering this! ANYTHING will do!

**Comment by Dade916** [comment] 2020-06-04 15:01
Discussed here: https://forums.luxcorerender.org/viewtopic.php?f=5&t=2231

**Comment by Dade916** [comment] 2020-06-04 15:06
Duplicate of https://github.com/LuxCoreRender/BlendLuxCore/issues/59

**Closed** 2020-06-14 20:50 UTC
