### ISSUE TITLE
LuxCor 2.3 on MacOs 10.14.6 (iMac2019) with Blender 28.2a no function

### ISSUE THREAD

**Issue by bense62** [LuxCoreRender/BlendLuxCore#479] opened 2020-06-05 14:40 UTC
<img width="709" alt="report error 2020-06-05_16 26 37" src="https://user-images.githubusercontent.com/66480895/83889028-ee8f2b00-a74a-11ea-8f6d-28b8a9aafc84.png">

**Comment by Theverat** [comment] 2020-06-05 16:16
Duplicate of #449

**Closed by Theverat** 2020-06-05 16:16 UTC
Labels: duplicate
