### ISSUE TITLE
Luxcore Pipeline Film is using unchecked OpenCL devices

### ISSUE THREAD

**Issue by iszotic** [LuxCoreRender/BlendLuxCore#250] opened 2019-03-21 23:40 UTC
#### System Information
Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic 64 Bits
GPU1 Vega 56
GPU2 RX480 8gb
#### Software Version
* Blender version: 2.79b
* LuxCore version: v2.1 and v2.2alpha
#### Short description of error
Hi, I have 2 GPU's, one Vega 56 and one RX480 8gb, so I installed AMDGPU-pro drivers 18.50, oddly enough these drivers recognize these GPUs as different OCL platforms, and they are unable to both be used in the same OpenCL application, then I installed Padoka's Mesa drivers with AMDGPU-pro drivers and this combination makes both GPU available for applications, the problem is that Mesa drivers are faulty.

In Blender there are 4 devices, 2 from mesa and 2 from amdgpu-pro, so I uncheck the two faulty mesa devices in the render panel, but Luxcore uses the first device in the list, a mesa device, for Luxcore image pipeline and tries to compile Film OpenCL, and it fails. The workaround is to uncheck OpenCL in the image pipeline bypassing the last compilation and making use of both GPU's for rendering, but the viewport gets slow because it's using only the CPU.

#### Error message from Blender console
This is the error message when it tries to render, you can see that it compiles the "gfx900" and "Ellesmere" devices, Vega 56 and RX480 respectively, but it fails in the film step when it uses a mesa device that it's not supposed to use.

```
pyluxcore version: 2.1
Updating OpenCL device list
==================================================
[Engine/Final] Rendering layer "RenderLayer"
[Exporter] Creating session
[SDL][275.174] Camera type: perspective
[SDL][275.174] Camera position: Point[7.48113, -6.50764, 5.34367]
[SDL][275.174] Camera target: Point[6.82957, -5.89347, 4.89839]
[SDL][275.174] Camera clipping plane disabled
WARNING: Material "Material": Missing node tree
[SDL][275.176] Material definition: Surface_Material_140644601048584
[SDL][275.176] Scene objects count: 1
[SDL][275.176] Light definition: Lamp_Lamp_140644601045512
[SDL][275.176] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][275.203] Configuration: 
[LuxCore][275.203]   path.pathdepth.total = 7
[LuxCore][275.203]   path.pathdepth.diffuse = 5
[LuxCore][275.203]   path.pathdepth.glossy = 5
[LuxCore][275.203]   path.pathdepth.specular = 6
[LuxCore][275.203]   opencl.cpu.use = 0
[LuxCore][275.203]   opencl.gpu.use = 1
[LuxCore][275.203]   opencl.devices.select = "0011"
[LuxCore][275.203]   sampler.sobol.adaptive.strength = 0.69999998807907104
[LuxCore][275.203]   sampler.random.adaptive.strength = 0.69999998807907104
[LuxCore][275.203]   sampler.metropolis.largesteprate = 0.40000000000000002
[LuxCore][275.203]   sampler.metropolis.maxconsecutivereject = 512
[LuxCore][275.203]   sampler.metropolis.imagemutationrate = 0.10000000000000001
[LuxCore][275.204]   film.filter.width = 1.5
[LuxCore][275.204]   lightstrategy.type = "LOG_POWER"
[LuxCore][275.204]   film.height = 540
[LuxCore][275.204]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][275.204]   scene.epsilon.min = 9.9999997473787516e-06
[LuxCore][275.204]   sampler.type = "SOBOL"
[LuxCore][275.204]   scene.epsilon.max = 0.10000000149011612
[LuxCore][275.204]   renderengine.type = "PATHOCL"
[LuxCore][275.204]   film.opencl.enable = 1
[LuxCore][275.204]   film.width = 960
[LuxCore][275.204]   path.forceblackbackground.enable = 0
[LuxCore][275.204]   renderengine.seed = 1
[LuxCore][275.204]   film.outputs.0.type = "RGB_IMAGEPIPELINE"
[LuxCore][275.204]   film.outputs.0.index = 0
[LuxCore][275.204]   film.outputs.0.filename = "RGB_IMAGEPIPELINE_0.png"
[LuxCore][275.204]   film.imagepipelines.0.0.type = "NOP"
[LuxCore][275.204]   film.imagepipelines.0.1.type = "TONEMAP_AUTOLINEAR"
[LuxCore][275.204]   film.imagepipelines.0.2.type = "TONEMAP_LINEAR"
[LuxCore][275.204]   film.imagepipelines.0.2.scale = 0.5
[LuxCore][275.204]   film.imagepipelines.0.radiancescales.0.enabled = 1
[LuxCore][275.204]   film.imagepipelines.0.radiancescales.0.globalscale = 1
[LuxCore][275.204]   film.imagepipelines.0.radiancescales.0.rgbscale = 1 1 1
[LuxCore][275.204]   batch.haltspp = 0
[LuxCore][275.204]   batch.halttime = 0
[LuxCore][275.204]   batch.haltthreshold = 0.0001
[LuxCore][275.204]   batch.haltthreshold.stoprendering.enable = 0
[LuxCore][275.204] File Name Resolver Configuration: 
Export took 0.0 s
[LuxCore][275.204] Film resolution: 960x540
[SDL][275.204] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][275.204] Image pipeline: film.imagepipelines.0
[SDL][275.204] Image pipeline step 0: NOP
[SDL][275.204] Image pipeline step 1: TONEMAP_AUTOLINEAR
[SDL][275.204] Image pipeline step 2: TONEMAP_LINEAR
[SDL][275.204] Film output definition: RGB_IMAGEPIPELINE [RGB_IMAGEPIPELINE_0.png]
[LuxRays][275.206] OpenCL Platform 0: Mesa
[LuxRays][275.206] OpenCL Platform 1: Advanced Micro Devices, Inc.
[LuxRays][275.206] OpenCL Platform 2: Advanced Micro Devices, Inc.
[LuxRays][275.207] Device 0 name: NativeThread
[LuxRays][275.207] Device 0 type: NATIVE_THREAD
[LuxRays][275.207] Device 0 compute units: 1
[LuxRays][275.207] Device 0 preferred float vector width: 4
[LuxRays][275.207] Device 0 max allocable memory: 0MBytes
[LuxRays][275.207] Device 0 max allocable memory block size: 0MBytes
[LuxRays][275.207] Device 1 name: Radeon RX Vega (VEGA10, DRM 3.27.0, 4.15.0-46-generic, LLVM 9.0.0)
[LuxRays][275.207] Device 1 type: OPENCL_GPU
[LuxRays][275.207] Device 1 compute units: 56
[LuxRays][275.207] Device 1 preferred float vector width: 4
[LuxRays][275.207] Device 1 max allocable memory: 26163MBytes
[LuxRays][275.207] Device 1 max allocable memory block size: 6540MBytes
[LuxRays][275.207] Device 2 name: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.27.0, 4.15.0-46-generic, LLVM 9.0.0)
[LuxRays][275.207] Device 2 type: OPENCL_GPU
[LuxRays][275.207] Device 2 compute units: 36
[LuxRays][275.207] Device 2 preferred float vector width: 4
[LuxRays][275.207] Device 2 max allocable memory: 26214MBytes
[LuxRays][275.207] Device 2 max allocable memory block size: 6553MBytes
[LuxRays][275.207] Device 3 name: gfx900
[LuxRays][275.207] Device 3 type: OPENCL_GPU
[LuxRays][275.207] Device 3 compute units: 56
[LuxRays][275.207] Device 3 preferred float vector width: 1
[LuxRays][275.207] Device 3 max allocable memory: 8176MBytes
[LuxRays][275.207] Device 3 max allocable memory block size: 4048MBytes
[LuxRays][275.207] Device 4 name: Ellesmere
[LuxRays][275.207] Device 4 type: OPENCL_GPU
[LuxRays][275.207] Device 4 compute units: 36
[LuxRays][275.207] Device 4 preferred float vector width: 1
[LuxRays][275.207] Device 4 max allocable memory: 8152MBytes
[LuxRays][275.207] Device 4 max allocable memory block size: 4048MBytes
[LuxRays][275.207] Creating 18 intersection device(s)
[LuxRays][275.207] Allocating intersection device 0: gfx900 (Type = OPENCL_GPU)
[LuxRays][275.207] Allocating intersection device 1: Ellesmere (Type = OPENCL_GPU)
[LuxRays][275.207] Allocating intersection device 2: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 3: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 4: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 5: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 6: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 7: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 8: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 9: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 10: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 11: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 12: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 13: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 14: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 15: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 16: NativeThread (Type = NATIVE_THREAD)
[LuxRays][275.207] Allocating intersection device 17: NativeThread (Type = NATIVE_THREAD)
[LuxCore][275.207] OpenCL devices used:
[LuxCore][275.207] [gfx900 Intersect]
[LuxCore][275.207]   Device OpenCL version: OpenCL 2.0 AMD-APP (2766.4)
[LuxCore][275.207] [Ellesmere Intersect]
[LuxCore][275.207]   Device OpenCL version: OpenCL 1.2 AMD-APP (2766.4)
[LuxCore][275.207] Native devices used: 16
[LuxCore][275.207] Configuring 2 OpenCL render threads
[LuxCore][275.207] Configuring 16 native render threads
[LuxRays][275.207] Preprocessing DataSet
[LuxRays][275.207] Total vertex count: 24
[LuxRays][275.207] Total triangle count: 12
[LuxRays][275.207] Preprocessing DataSet done
[LuxRays][275.207] Adding DataSet accelerator: BVH
[LuxRays][275.207] Total vertex count: 24
[LuxRays][275.207] Total triangle count: 12
[LuxRays][275.210] BVH Dataset preprocessing time: 2ms
[LuxRays][275.210] BVH builder: EMBREE_BINNED_SAH
[LuxRays][275.210] BVH build hierarchy time: 0ms
[LuxRays][275.210] BVH total build time: 3ms
[LuxRays][275.210] Total BVH memory usage: 0Kbytes
[LuxRays][275.210] Adding DataSet accelerator: EMBREE
[LuxRays][275.210] Total vertex count: 24
[LuxRays][275.210] Total triangle count: 12
[LuxRays][275.211] EmbreeAccel build time: 0ms
[LuxRays][275.409] [Device gfx900 Intersect] BVH mesh vertices buffer size: 288bytes
[LuxRays][275.409] [Device gfx900 Intersect] BVH nodes buffer size: 608bytes
[LuxRays][275.602] [Device Ellesmere Intersect] BVH mesh vertices buffer size: 288bytes
[LuxRays][275.602] [Device Ellesmere Intersect] BVH nodes buffer size: 608bytes
[LuxCore][275.756] Building visibility map of light source: __WORLD_BACKGROUND_LIGHT__
[LuxCore][275.756] Using 16 threads for visibility map building
[LuxCore][275.839] Visibility map done in 0.08 secs with 1000000 samples (12.13M samples/sec)
[LuxCore][275.853] [PathOCLRenderEngine] OpenCL task count: 524288
[LuxCore][275.854] [PathOCLBaseRenderEngine] OpenCL max. page memory size: 4145152Kbytes
[LuxCore][275.854] Compile Geometry
[LuxCore][275.854] Scene geometry compilation time: 0ms
[LuxCore][275.854] Compile 1 Textures
[LuxCore][275.854] Textures compilation time: 0ms
[LuxCore][275.854] Compile 1 Materials
[LuxCore][275.854] Material compilation time: 0ms
[LuxCore][275.854] Compile Lights
[LuxCore][275.855] Lights compilation time: 1ms
[LuxCore][275.855] Compile ImageMaps
[LuxCore][275.855] Image maps page(s) count: 0
[LuxCore][275.855] Image maps compilation time: 0ms
[LuxCore][275.855] Always enabled OpenCL code: 
[LuxCore][275.855] Compile Geometry
[LuxCore][275.855] Scene geometry compilation time: 0ms
[LuxCore][275.856] Compile 1 Textures
[LuxCore][275.856] Textures compilation time: 0ms
[LuxCore][275.856] Compile 1 Materials
[LuxCore][275.856] Material compilation time: 0ms
[LuxCore][275.856] Compile Lights
[LuxCore][275.856] Lights compilation time: 0ms
[LuxCore][275.856] Compile ImageMaps
[LuxCore][275.856] Image maps page(s) count: 0
[LuxCore][275.856] Image maps compilation time: 0ms
[LuxCore][275.856] Starting 2 OpenCL render threads
[LuxRays][275.864] [Device gfx900 Intersect] RADIANCE_PER_PIXEL_NORMALIZEDs[0] buffer size: 8100Kbytes
[LuxRays][275.865] [Device gfx900 Intersect] CONVERGENCE buffer size: 2025Kbytes
[LuxRays][275.874] [Device gfx900 Intersect] RADIANCE_PER_PIXEL_NORMALIZEDs[0] buffer size: 8100Kbytes
[LuxRays][275.874] [Device gfx900 Intersect] Camera buffer size: 5448bytes
[LuxRays][275.874] [Device gfx900 Intersect] Normals buffer size: 288bytes
[LuxRays][275.874] [Device gfx900 Intersect] Vertices buffer size: 288bytes
[LuxRays][275.874] [Device gfx900 Intersect] Triangles buffer size: 144bytes
[LuxRays][275.874] [Device gfx900 Intersect] Mesh description buffer size: 156bytes
[LuxRays][275.874] [Device gfx900 Intersect] Textures buffer size: 272bytes
[LuxRays][275.874] [Device gfx900 Intersect] Materials buffer size: 132bytes
[LuxRays][275.874] [Device gfx900 Intersect] Scene objects buffer size: 12bytes
[LuxRays][275.874] [Device gfx900 Intersect] Lights buffer size: 656bytes
[LuxRays][275.875] [Device gfx900 Intersect] Env. light indices buffer size: 4bytes
[LuxRays][275.875] [Device gfx900 Intersect] Light offsets (Part I) buffer size: 4bytes
[LuxRays][275.875] [Device gfx900 Intersect] Env. light distributions buffer size: 1028Kbytes
[LuxRays][275.875] [Device gfx900 Intersect] LightsDistribution buffer size: 24bytes
[LuxRays][275.875] [Device gfx900 Intersect] InfiniteLightSourcesDistribution buffer size: 24bytes
[LuxRays][275.876] [Device gfx900 Intersect] Ray buffer size: 24576Kbytes
[LuxRays][275.876] [Device gfx900 Intersect] RayHit buffer size: 10240Kbytes
[LuxCore][275.876] [PathOCLBaseRenderThread::0] Size of a GPUTask: 132bytes
[LuxRays][275.876] [Device gfx900 Intersect] GPUTask buffer size: 67584Kbytes
[LuxCore][275.878] [PathOCLBaseRenderThread::0] Size of a GPUTask DirectLight: 80bytes
[LuxRays][275.878] [Device gfx900 Intersect] GPUTaskDirectLight buffer size: 40960Kbytes
[LuxCore][275.879] [PathOCLBaseRenderThread::0] Size of a GPUTask State: 200bytes
[LuxRays][275.879] [Device gfx900 Intersect] GPUTaskState buffer size: 102400Kbytes
[LuxRays][275.880] [Device gfx900 Intersect] GPUTask Stats buffer size: 2048Kbytes
[LuxRays][275.880] [Device gfx900 Intersect] SamplerSharedData buffer size: 126Kbytes
[LuxCore][275.881] [PathOCLBaseRenderThread::0] Size of a Sample: 84bytes
[LuxRays][275.881] [Device gfx900 Intersect] Sample buffer size: 43008Kbytes
[LuxCore][275.882] [PathOCLBaseRenderThread::0] Sample dimensions: 54
[LuxCore][275.882] [PathOCLBaseRenderThread::0] Size of a SampleData: 8bytes
[LuxRays][275.882] [Device gfx900 Intersect] SampleData buffer size: 4096Kbytes
[LuxRays][275.882] [Device gfx900 Intersect] Pixel Filter Distribution buffer size: 33Kbytes
[LuxCore][275.884] [PathOCLBaseRenderThread::0] Defined symbols:  -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL -D RENDER_ENGINE_PATHOCL -D PARAM_RAY_EPSILON_MIN=1.000000e-05f -D PARAM_RAY_EPSILON_MAX=1.000000e-01f -D PARAM_LIGHT_WORLD_RADIUS_SCALE=1.050000e+00f -D PARAM_ACCEL_BVH -D PARAM_FILM_RADIANCE_GROUP_0 -D PARAM_FILM_RADIANCE_GROUP_COUNT=1 -D PARAM_FILM_CHANNELS_HAS_CONVERGENCE -D PARAM_ENABLE_TEX_CONST_FLOAT -D PARAM_ENABLE_TEX_CONST_FLOAT3 -D PARAM_ENABLE_TEX_IMAGEMAP -D PARAM_ENABLE_TEX_NORMALMAP -D PARAM_ENABLE_TEX_FRESNELCOLOR -D PARAM_ENABLE_TEX_FRESNELCONST -D PARAM_ENABLE_MAT_MATTE -D PARAM_CAMERA_TYPE=0 -D PARAM_HAS_SKYLIGHT2 -D PARAM_HAS_POINTLIGHT -D PARAM_HAS_ENVLIGHTS -D PARAM_MAX_PATH_DEPTH=7 -D PARAM_MAX_PATH_DEPTH_DIFFUSE=5 -D PARAM_MAX_PATH_DEPTH_GLOSSY=5 -D PARAM_MAX_PATH_DEPTH_SPECULAR=6 -D PARAM_RR_DEPTH=3 -D PARAM_RR_CAP=5.000000e-01f -D PARAM_SQRT_VARIANCE_CLAMP_MAX_VALUE=0.000000e+00f -D PARAM_IMAGE_FILTER_TYPE=5 -D PARAM_IMAGE_FILTER_WIDTH_X=1.500000e+00f -D PARAM_IMAGE_FILTER_WIDTH_Y=1.500000e+00f -D PARAM_IMAGE_FILTER_PIXEL_WIDTH_X=1 -D PARAM_IMAGE_FILTER_PIXEL_WIDTH_Y=1 -D PARAM_SAMPLER_TYPE=2 -D PARAM_SAMPLER_SOBOL_STARTOFFSET=32
[LuxCore][275.884] [PathOCLBaseRenderThread::0] Compiling kernels 
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Kernels cached
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling Film_Clear Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling InitSeed Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling Init Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_RT_NEXT_VERTEX Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_HIT_NOTHING Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_HIT_OBJECT Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_RT_DL Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_DL_ILLUMINATE Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_DL_SAMPLE_BSDF Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_GENERATE_NEXT_VERTEX_RAY Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_SPLAT_SAMPLE Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_NEXT_SAMPLE Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Compiling AdvancePaths_MK_GENERATE_CAMERA_RAY Kernel
[LuxCore][275.891] [PathOCLBaseRenderThread::0] Kernels compilation time: 8ms
[LuxRays][275.899] [Device Ellesmere Intersect] RADIANCE_PER_PIXEL_NORMALIZEDs[0] buffer size: 8100Kbytes
[LuxRays][275.899] [Device Ellesmere Intersect] CONVERGENCE buffer size: 2025Kbytes
[LuxRays][275.907] [Device Ellesmere Intersect] RADIANCE_PER_PIXEL_NORMALIZEDs[0] buffer size: 8100Kbytes
[LuxRays][275.907] [Device Ellesmere Intersect] Camera buffer size: 5448bytes
[LuxRays][275.907] [Device Ellesmere Intersect] Normals buffer size: 288bytes
[LuxRays][275.907] [Device Ellesmere Intersect] Vertices buffer size: 288bytes
[LuxRays][275.907] [Device Ellesmere Intersect] Triangles buffer size: 144bytes
[LuxRays][275.908] [Device Ellesmere Intersect] Mesh description buffer size: 156bytes
[LuxRays][275.908] [Device Ellesmere Intersect] Textures buffer size: 272bytes
[LuxRays][275.908] [Device Ellesmere Intersect] Materials buffer size: 132bytes
[LuxRays][275.908] [Device Ellesmere Intersect] Scene objects buffer size: 12bytes
[LuxRays][275.908] [Device Ellesmere Intersect] Lights buffer size: 656bytes
[LuxRays][275.908] [Device Ellesmere Intersect] Env. light indices buffer size: 4bytes
[LuxRays][275.908] [Device Ellesmere Intersect] Light offsets (Part I) buffer size: 4bytes
[LuxRays][275.908] [Device Ellesmere Intersect] Env. light distributions buffer size: 1028Kbytes
[LuxRays][275.909] [Device Ellesmere Intersect] LightsDistribution buffer size: 24bytes
[LuxRays][275.909] [Device Ellesmere Intersect] InfiniteLightSourcesDistribution buffer size: 24bytes
[LuxRays][275.910] [Device Ellesmere Intersect] Ray buffer size: 24576Kbytes
[LuxRays][275.910] [Device Ellesmere Intersect] RayHit buffer size: 10240Kbytes
[LuxCore][275.910] [PathOCLBaseRenderThread::1] Size of a GPUTask: 132bytes
[LuxRays][275.910] [Device Ellesmere Intersect] GPUTask buffer size: 67584Kbytes
[LuxCore][275.910] [PathOCLBaseRenderThread::1] Size of a GPUTask DirectLight: 80bytes
[LuxRays][275.910] [Device Ellesmere Intersect] GPUTaskDirectLight buffer size: 40960Kbytes
[LuxCore][275.910] [PathOCLBaseRenderThread::1] Size of a GPUTask State: 200bytes
[LuxRays][275.910] [Device Ellesmere Intersect] GPUTaskState buffer size: 102400Kbytes
[LuxRays][275.911] [Device Ellesmere Intersect] GPUTask Stats buffer size: 2048Kbytes
[LuxRays][275.911] [Device Ellesmere Intersect] SamplerSharedData buffer size: 126Kbytes
[LuxCore][275.911] [PathOCLBaseRenderThread::1] Size of a Sample: 84bytes
[LuxRays][275.911] [Device Ellesmere Intersect] Sample buffer size: 43008Kbytes
[LuxCore][275.911] [PathOCLBaseRenderThread::1] Sample dimensions: 54
[LuxCore][275.911] [PathOCLBaseRenderThread::1] Size of a SampleData: 8bytes
[LuxRays][275.911] [Device Ellesmere Intersect] SampleData buffer size: 4096Kbytes
[LuxRays][275.912] [Device Ellesmere Intersect] Pixel Filter Distribution buffer size: 33Kbytes
[LuxCore][275.914] [PathOCLBaseRenderThread::1] Defined symbols:  -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL -D RENDER_ENGINE_PATHOCL -D PARAM_RAY_EPSILON_MIN=1.000000e-05f -D PARAM_RAY_EPSILON_MAX=1.000000e-01f -D PARAM_LIGHT_WORLD_RADIUS_SCALE=1.050000e+00f -D PARAM_ACCEL_BVH -D PARAM_FILM_RADIANCE_GROUP_0 -D PARAM_FILM_RADIANCE_GROUP_COUNT=1 -D PARAM_FILM_CHANNELS_HAS_CONVERGENCE -D PARAM_ENABLE_TEX_CONST_FLOAT -D PARAM_ENABLE_TEX_CONST_FLOAT3 -D PARAM_ENABLE_TEX_IMAGEMAP -D PARAM_ENABLE_TEX_NORMALMAP -D PARAM_ENABLE_TEX_FRESNELCOLOR -D PARAM_ENABLE_TEX_FRESNELCONST -D PARAM_ENABLE_MAT_MATTE -D PARAM_CAMERA_TYPE=0 -D PARAM_HAS_SKYLIGHT2 -D PARAM_HAS_POINTLIGHT -D PARAM_HAS_ENVLIGHTS -D PARAM_MAX_PATH_DEPTH=7 -D PARAM_MAX_PATH_DEPTH_DIFFUSE=5 -D PARAM_MAX_PATH_DEPTH_GLOSSY=5 -D PARAM_MAX_PATH_DEPTH_SPECULAR=6 -D PARAM_RR_DEPTH=3 -D PARAM_RR_CAP=5.000000e-01f -D PARAM_SQRT_VARIANCE_CLAMP_MAX_VALUE=0.000000e+00f -D PARAM_IMAGE_FILTER_TYPE=5 -D PARAM_IMAGE_FILTER_WIDTH_X=1.500000e+00f -D PARAM_IMAGE_FILTER_WIDTH_Y=1.500000e+00f -D PARAM_IMAGE_FILTER_PIXEL_WIDTH_X=1 -D PARAM_IMAGE_FILTER_PIXEL_WIDTH_Y=1 -D PARAM_SAMPLER_TYPE=2 -D PARAM_SAMPLER_SOBOL_STARTOFFSET=32
[LuxCore][275.914] [PathOCLBaseRenderThread::1] Compiling kernels 
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Kernels cached
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling Film_Clear Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling InitSeed Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling Init Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_RT_NEXT_VERTEX Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_HIT_NOTHING Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_HIT_OBJECT Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_RT_DL Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_DL_ILLUMINATE Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_DL_SAMPLE_BSDF Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_GENERATE_NEXT_VERTEX_RAY Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_SPLAT_SAMPLE Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_NEXT_SAMPLE Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Compiling AdvancePaths_MK_GENERATE_CAMERA_RAY Kernel
[LuxCore][275.922] [PathOCLBaseRenderThread::1] Kernels compilation time: 10ms
[LuxCore][275.923] Starting 16 native render threads
[LuxCore][275.939] Film OpenCL image pipeline
[LuxCore][275.939] Film OpenCL Device used: Radeon RX Vega (VEGA10, DRM 3.27.0, 4.15.0-46-generic, LLVM 9.0.0) Intersect
[LuxCore][275.939]   Device OpenCL version: OpenCL 1.1 Mesa 19.1.0-devel - padoka PPA
[LuxRays][276.675] [Device Radeon RX Vega (VEGA10, DRM 3.27.0, 4.15.0-46-generic, LLVM 9.0.0) Intersect] IMAGEPIPELINE buffer size: 6075Kbytes
[LuxRays][276.678] [Device Radeon RX Vega (VEGA10, DRM 3.27.0, 4.15.0-46-generic, LLVM 9.0.0) Intersect] Merge buffer size: 8100Kbytes
[LuxCore][276.678] [MergeSampleBuffersOCL] Defined symbols: -D LUXRAYS_OPENCL_KERNEL -D SLG_OPENCL_KERNEL
[LuxCore][276.678] [MergeSampleBuffersOCL] Compiling kernels 
[LuxCore][276.679] [MergeSampleBuffersOCL] Kernels cached
[LuxCore][276.679] [MergeSampleBuffersOCL] Compiling Film_MergeBufferInitialize Kernel
[LuxCore][276.679] [MergeSampleBuffersOCL] Compiling Film_MergeRADIANCE_PER_PIXEL_NORMALIZED Kernel
[LuxCore][276.679] [MergeSampleBuffersOCL] Compiling Film_MergeRADIANCE_PER_SCREEN_NORMALIZED Kernel
[LuxCore][276.679] [MergeSampleBuffersOCL] Compiling Film_MergeBufferFinalize Kernel
[LuxCore][276.679] [MergeSampleBuffersOCL] Kernels compilation time: 0ms
./blender: symbol lookup error: /usr/lib/x86_64-linux-gnu/gallium-pipe/pipe_radeonsi.so: undefined symbol: amdgpu_cs_submit_raw2
```

**Comment by Dade916** [comment] 2019-03-22 10:57
> #### Short description of error
> Hi, I have 2 GPU's, one Vega 56 and one RX480 8gb, so I installed AMDGPU-pro drivers 18.50, oddly enough these drivers recognize these GPUs as different OCL platforms, and they are unable to both be used in the same OpenCL application

Uh, why ? LuxCore supports and can use devices on multiple OpenCL platforms. As proof, you have seen it shows both the devices available on Mesa and AMD platform. I use every day devices from AMD and NVIDIA platform everyday.

Looking at the error, it seems your Mesa installation is also broken. This is quite common when you install both Mesa and Vendor GPU drivers.

So, in may opinion, you should go back to square one, uninstall Mesa drivers (and probably re-install AMD drivers because Mesa may have broken the OpenGL installation). At that point, let me know what kind of problem do you have.

Back in topic: LuxCore supports the selection of OpenCL device where to run the image pipeline but I'm afraid this feature is not exposed in Blender. So you could hack the python code to add an hard coded image pipeline device selection but, as I wrote before, it may be better to fix the problem at the root.

**Comment by Theverat** [comment] 2019-03-22 11:22
> Back in topic: LuxCore supports the selection of OpenCL device where to run the image pipeline but I'm afraid this feature is not exposed in Blender.

https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.1#Film_OpenCL_Options
I can add support for this in the addon.

**Comment by Dade916** [comment] 2019-03-22 11:25
> > Back in topic: LuxCore supports the selection of OpenCL device where to run the image pipeline but I'm afraid this feature is not exposed in Blender.
> 
> https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.1#Film_OpenCL_Options
> I can add support for this in the addon.

It should be pretty much a duplicate of the same rendering devices panel with the difference that only a single selection is allowed.

**Closed** 2019-03-22 12:54 UTC

**Comment by Theverat** [comment] 2019-03-22 12:55
A have added a new device selection dropdown to the right of the "Use OpenCL" checkbox in the imagepipeline settings.
