### ISSUE TITLE
Activate error

### ISSUE THREAD

**Issue by maljos** [LuxCoreRender/BlendLuxCore#502] opened 2020-07-02 07:01 UTC
.blend file: 

Steps to reproduce:

Screenshots or rendered images:
![Captura de pantalla_2020-07-02_02-52-01](https://user-images.githubusercontent.com/3738917/86326756-2b4a2700-bc10-11ea-9014-39d4db8a558a.png)

Error message from Blender console:

OS: Xubuntu 18.04
Blender version: 2.83
LuxCore version: 2.4 beta1

**Comment by Theverat** [comment] 2020-07-02 10:20
Your addon installation might be broken.
Can you try to delete it and re-install it?

**Comment by maljos** [comment] 2020-07-02 18:00
Thanks

**Comment by maljos** [comment] 2020-07-02 18:44
I update my python modules and i can activate. Now, i was able to renderer a scene perfectly, later, when I activated the lights cache, the blender crash closed. I deactivated the blendluxcore and tried to activate it again it gives me another error:
![Captura de pantalla_2020-07-02_14-41-30](https://user-images.githubusercontent.com/3738917/86397648-3a61c100-bc72-11ea-897c-721f88f03562.png)

**Comment by Theverat** [comment] 2020-07-02 19:44
Yeah, I also noticed something is wrong with node category unregistering/registering.
I have looked into it a bit but haven't found the cause of the problem yet, unfortunately.

If you restart Blender, you should be able to activate the addon though.

**Comment by maljos** [comment] 2020-07-02 20:06
I had to reinstall blender 2.83 and re-activated the program, it works again

**Comment by Theverat** [comment] 2020-07-02 21:41
> Yeah, I also noticed something is wrong with node category unregistering/registering.
I have looked into it a bit but haven't found the cause of the problem yet, unfortunately.

Fixed in 0f8f7c156e322ed793e61d0ba3e73d21c61cf099.

**Closed by Theverat** 2020-07-02 21:41 UTC
