### ISSUE TITLE
Random compiling of CUDA kernels

### ISSUE THREAD

**Issue by johndow16** [LuxCoreRender/BlendLuxCore#652] opened 2021-03-20 04:26 UTC
Windows 10 x64 (2004 19041.867)
Blender 2.92
GTX1660 (461.92)

LuxCore 2.5RC1 randomly compiles CUDA kernels. It happens all of sudden and out of nowhere. I was rendering frames and BAM! it started compiling CUDA kernels. I was trying different camera angles in viewport (GPU w/o denoiser) and BAM! it suddenly started compiling CUDA kernels. It happens quite often and I couldn't pinpoint the issue. Material change, camera switch, shader tweak, change in a model... Anything can trigger it.

**Comment by Theverat** [comment] 2021-03-20 09:49
Closing this as it's a duplicate of https://github.com/LuxCoreRender/LuxCore/issues/513

**Closed by Theverat** 2021-03-20 09:49 UTC
