### ISSUE TITLE
Can't install on Mac -- Mac Pro 8 core 2013 - OS 10.14.6

### ISSUE THREAD

**Issue by teamoffsite** [LuxCoreRender/BlendLuxCore#376] opened 2020-02-06 23:31 UTC
Crashes blender on install. Desperately need mac version.
We install the zip for the addon, select addon, crash on checkbox.
Tried Blender 2.81, 2.82b

**Comment by Theverat** [comment] 2020-02-07 00:12
Possibly a duplicate of #372?

**Comment by zebus3d** [comment] 2020-03-16 16:11
I have the same issue.

**Comment by u3dreal** [comment] 2020-04-10 08:36
2.3 should now work with Mojave and Catalina . Use up to Blender 2.81a for 2.3 release.
updated now
[https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.3](url)

**Closed by u3dreal** 2020-04-10 08:36 UTC
