### ISSUE TITLE
denoisers don't work under linux

### ISSUE THREAD

**Issue by crazyrobinhood** [LuxCoreRender/BlendLuxCore#475] opened 2020-06-03 15:17 UTC
Apparently post rendering denoisers don't work under linux (popOS!)
In viewport preview OIDN works just fine.
It doesn't crash but is not visible in the final render.

Blender version 2.82a stable
Blenderluxcore version 2.4 alpha

OS: Pop!_OS 20.04 LTS x86_64 
Kernel: 5.4.0-7634-generic 
Shell: bash 5.0.16 
Resolution: 1920x1200, 1920x1200 
DE: GNOME 
CPU: Intel i5-2320 (4) @ 3.300GHz 
GPU: NVIDIA GeForce GTX 1060 6GB 
Memory: 3539MiB / 7927MiB

**Comment by guismoale** [comment] 2020-06-09 08:23
Second that. It crashes here. It says "segmentation fault (core dumped).
Blender 2.83 stable
Blenderluxcores 2.3 opencl
Ubuntu 18.04.2 64bits
Ryzen 3800x
Nvidia gtx 1050 ti
32GB memory

**Comment by guismoale** [comment] 2020-06-09 08:27
Actually, sorry. OIDN is the one that crashes. BCD works... I think. I don't quite understand because it only works when I use the denoiser node on the compositor. If I don't have the luxcore denoiser enabled the node does nothing. But if I try to use OIDN then it just crashes after some time rendering.

**Comment by Dade916** [comment] 2020-06-11 10:23
This should be a duplicate of #423. The discussion can continue in other issue.

**Closed by Dade916** 2020-06-11 10:23 UTC
Labels: duplicate
