### ISSUE TITLE
Can't Install Luxcore on Blender

### ISSUE THREAD

**Issue by FroyoFire** [LuxCoreRender/BlendLuxCore#723] opened 2021-08-25 04:30 UTC
![messageImage_1629865686535](https://user-images.githubusercontent.com/89502861/130726641-c065e303-8e9b-42fa-a854-6060631c0858.jpg)
i have install the C++ Package but it still don't work

**Comment by Dade916** [comment] 2021-08-25 09:57
Duplicate of #724.

**Closed by Dade916** 2021-08-25 09:57 UTC
