### ISSUE TITLE
node wrangler like fetures not working in lates luxcore

### ISSUE THREAD

**Issue by SlincHD** [LuxCoreRender/BlendLuxCore#802] opened 2023-01-07 17:12 UTC
blender 3.4.1

any shader

using ctrl+shift+click to watch the node makes this error:

"Python: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BlendLuxCore\operators\node_editor.py", line 54, in invoke
    select_node = bpy.ops.node.select(mouse_x=event.mouse_region_x, mouse_y=event.mouse_region_y, extend=False)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "mouse_x" unrecognized"

**Comment by neo2068** [comment] 2023-04-03 08:02
Duplicate of #780

**Closed** 2023-04-03 08:03 UTC
